### ISSUE TITLE
 electron-ssr-0.2.5.deb 安装失败

### ISSUE THREAD

**Issue by HonestKwong** [pyexile/Notes#50]
出错信息如下：

$ sudo dpkg -i electron-ssr-0.2.5.deb
dpkg-deb: 错误: 'electron-ssr-0.2.5.deb' is not a Debian format archive
dpkg: 处理归档 electron-ssr-0.2.5.deb (--install)时出错：
 dpkg-deb --control subprocess returned error exit status 2
在处理时有错误发生：
 electron-ssr-0.2.5.deb

请问一下这个有什么解决办法吗

**Comment by pyexile** [comment]
这儿有个类似的错误，你可以参考一下：https://github.com/duplicati/duplicati/issues/2936。
另外，该软件是从https://github.com/qingshuisiyuan/electron-ssr-backup这儿看到的，你可以参考原文

**Comment by MiChongGET** [comment]
ubuntu19.10安装完成之后，点击图标，出现终端，然后闪退

**Comment by HonestKwong** [comment]
> 这儿有个类似的错误，你可以参考一下：[https://github.com/duplicati/duplicati/issues/2936。](https://github.com/duplicati/duplicati/issues/2936%E3%80%82)
> 另外，该软件是从https://github.com/qingshuisiyuan/electron-ssr-backup，这儿看到的，你可以参考原文

**Comment by HonestKwong** [comment]
> 这儿有个类似的错误，你可以参考一下：[https://github.com/duplicati/duplicati/issues/2936。](https://github.com/duplicati/duplicati/issues/2936%E3%80%82)
> 另外，该软件是从https://github.com/qingshuisiyuan/electron-ssr-backup，这儿看到的，你可以参考原文
谢谢帮助~~
